# From: https://github.com/rkdarst/sphinx-actions-test/blob/master/.github/workflows/sphinx-build.yml

name: sphinx
on: 
  push:
    branches: [main]
  pull_request: {}

env:
  DEFAULT_BRANCH: main
  #SPHINXOPTS: "-W --keep-going -T"
  # ^-- If these SPHINXOPTS are enabled, then be strict about the builds and fail on any warnings

jobs:
  build-and-deploy:
    name: Build and Deploy on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Doxygen
        run: |
          sudo apt-get install -y doxygen

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@v3.20.1

      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "^3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: ~/.virtualenvs

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
            poetry-${{ runner.os }}-
            poetry-

      - name: Install Dependencies
        run: poetry install
        #if: steps.cache.outputs.cache-hit != 'true'

      - name: Debugging information
        run: |
          echo "github.ref:" ${{github.ref}}
          echo "github.event_name:" ${{github.event_name}}
          echo "github.head_ref:" ${{github.head_ref}}
          echo "github.base_ref:" ${{github.base_ref}}
          set -x
          git rev-parse --abbrev-ref HEAD
          git branch
          git branch -a
          git remote -v
          python -V
          pip list --not-required
          pip list

      - name: Configure CMake project
        shell: pwsh
        run: |
          poetry run cmake `
          -G Ninja `
          -D aes-c_SPHINX_FORMATS=html `
          -B build/

      # Build
      - uses: ammaraskar/sphinx-problem-matcher@master
      - name: Build Sphinx docs
        run: |
          #make dirhtml
          ninja -C build docs
          # This fixes broken copy button icons, as explained in
          #   https://github.com/coderefinery/sphinx-lesson/issues/50
          #   https://github.com/executablebooks/sphinx-copybutton/issues/110
          # This can be removed once these PRs are accepted (but the
          # fixes also need to propagate to other themes):
          #   https://github.com/sphinx-doc/sphinx/pull/8524
          #   https://github.com/readthedocs/sphinx_rtd_theme/pull/1025
          sed -i 's/url_root="#"/url_root=""/' build/docs/sphinx/html/index.html || true

      - name: Copy Sphinx docs to 'public' dir for publishing
        run: cp -r build/docs/sphinx/html public

      - name: Add the .nojekyll file
        run: touch public/.nojekyll

      # Deploy
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true

